### ISSUE TITLE
6.9.0 throws TypeError in stand-alone mode while writing out period number

### ISSUE THREAD

**Issue by DrPaulBrewer** [DrPaulBrewer/single-market-robot-simulator#35]
Error messages looked like this in Docker container

```
/work $ node ~/single-market-robot-simulator/build/index.js sim.json
internal/fs/utils.js:657
    throw new ERR_INVALID_ARG_TYPE(
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (1)
    at Object.writeFileSync (fs.js:1380:5)
    at mainPeriod (/home/node/single-market-robot-simulator/build/index.js:763:8)
    at Simulation.run (/home/node/single-market-robot-simulator/build/index.js:720:9)
    at main (/home/node/single-market-robot-simulator/build/index.js:767:26)
    at Object.<anonymous> (/home/node/single-market-robot-simulator/build/index.js:775:43)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by DrPaulBrewer** [comment]
This happens in the `fs.writeFileSync()` call when writing out the period number.

Apparently, the type checking for this call has become more strict.  It used to convert the number to a string but now it throws a TypeError instead.

It doesn't affect node version 12.18.1.

It does affect node version 14.4.0

**Comment by DrPaulBrewer** [comment]
`fs.writeFileSync` is only called in one place in single-market-robot-simulator, here:

https://github.com/DrPaulBrewer/single-market-robot-simulator/blob/76a6e066a32a21caa36ca173f6b7edf8cef22cf2/src/index.js#L751-L753

**Comment by DrPaulBrewer** [comment]
converting to string manually should fix

**Comment by DrPaulBrewer** [comment]
done
